### ISSUE TITLE
FAQ - When should I open registration for my local Coderetreat?

### ISSUE THREAD

**Issue by dlondero** [coderetreat/coderetreat.github.io#113]
In the answer there's "It’s recommended that you open registration on Thursday, September 22nd..." and then talk why opening registration 1 month before the event is good. I guess the above date was referring to some retreat happened in the past as with this year Sept 22nd - Nov 18th it's almost 2 months.

Should the text be rephrased to something like "It’s recommended that you open registration one month before the event:"?

Or maybe put the date of the GDCR in a config yml in _data and then use it in hero.html (all other places referring to GDCR date if any) and do some magic with Jekyll in order to calculate the date to suggest for opening registrations?

**Comment by apandichi** [comment]
Hi @dlondero!
You're right, any of the options you suggested are viable.
Pull requests are welcome! :smile:

**Comment by dlondero** [comment]
Ok I'll send a PR.

**Comment by apandichi** [comment]
Thank  you, @dlondero!
