### ISSUE TITLE
Remove flags from banner

### ISSUE THREAD

**Issue by rradczewski** [coderetreat/coderetreat.github.io#12]
![Screenshot of the homepage showing the problem](https://user-images.githubusercontent.com/418117/28362286-1d733e78-6c7c-11e7-8423-5f89fc27971a.png)

The SVG on [our landing page](http://gdcr.coderetreat.org/) has been broken for some time now. The problematic files are [this one](https://github.com/coderetreat/coderetreat.github.io/blob/master/images/mountain_path.svg) and [this one](https://github.com/coderetreat/coderetreat.github.io/blob/master/images/mountain_path_with_title.svg)

Easiest way is to just remove all the flags, a creative solution (without specific country flags) would be nice too.

**Comment by tpd-opitz** [comment]
done

**Comment by apandichi** [comment]
Fixed by pull request #29
