### ISSUE TITLE
Remove companies from `moderators` of events

### ISSUE THREAD

**Issue by rradczewski** [coderetreat/coderetreat.github.io#159]
This is something where I'd like your input on @apandichi @mplavcan @amirci (in the orga channel). I only just now (when merging #158) noticed that some of the events have `moderators` that are not actually moderators, but companies sponsoring or hosting events.

With us getting back to the roots of coderetreats, making them about communities and individuals and not having global sponsors and such, I'd personally prefer to remove those moderators from the events.

We could, should we decide to explicitly give exposure to the companies supporting coderetreats, introduce a new field `sponsors` next year.

What do you think?

**Comment by apandichi** [comment]
I agree.
I vote for removing the companies from moderators and add them to a
separate (optional) field of sponsors.
We shouldn't wait for next year, I don't see what's stopping us from doing
it right now. Apart from the manual work to review all the events...

Cheers,
Alin

**Comment by toubou91** [comment]
No worries guys, I/m working on that. You'll have a PR in around an hour.

**Comment by rradczewski** [comment]
Hey @toubou91,
Thanks for volunteering, but we have yet to make a decision about this ☺️ wouldn't want you to do the work for nothing should we decide for another solution for this year 👌😅

**Comment by toubou91** [comment]
I believe something like that is an easy and convenient fix for now:

![screen shot 2017-10-15 at 12 39 36](https://user-images.githubusercontent.com/5684688/31584012-01df8dc8-b1a6-11e7-9a32-b7e0c6cb2f15.png)

What do you think?

**Comment by rradczewski** [comment]
Fair enough, but I guess we'd need to rework the mobile view in that case, going for something more responsive than tables.

**Comment by toubou91** [comment]
Indeed, but first, we have to start from somewhere.
So, shall I continue with that?

**Comment by rradczewski** [comment]
Done ;)
