### ISSUE TITLE
Create timeline file for GDCR17

### ISSUE THREAD

**Issue by apandichi** [coderetreat/coderetreat.github.io#243]

**Comment by apandichi** [comment]
Timezone spreadsheet created: 
https://docs.google.com/spreadsheets/d/1cWnSSc0a6770FgkZkWIn1DgJX6qvwFaPs3D5xXgmbBM/edit#gid=883468950

We still need to embed it onto the website, maybe here: http://coderetreat.org/hosts/

**Comment by rradczewski** [comment]
Done  by linking to it 😊👌
