### ISSUE TITLE
Have the first training session with @mplavcan

### ISSUE THREAD

**Issue by rradczewski** [coderetreat/coderetreat.github.io#27]
August 7th ?

**Comment by rradczewski** [comment]
- [ ] Finalize Date
- [ ] Google Plus Event
- [ ] Twitter Announcement

**Comment by mplavcan** [comment]
August 7th, Event posted on [Google+](https://plus.google.com/u/0/events/c7fv4aoi90hr8gi76afttcs8krs)

**Comment by mplavcan** [comment]
[Twitter post] (https://twitter.com/mplavcan/status/890715971538763776)

**Comment by mplavcan** [comment]
[Twitter post](https://twitter.com/mplavcan/status/890715971538763776)
