### ISSUE TITLE
Make website SSL

### ISSUE THREAD

**Issue by coreyhaines** [coderetreat/coderetreat.github.io#275]
It is slightly more complicated on github.io, but Jen Myers has a great write-up here to front it with cloudflare. I believe their shared cert that comes with the free option should work, but would be worth investigating. 
https://jenmyers.net/using-https-with-github-pages-and-custom

If the shared cert doesn't work for us, then we could reach out to them (or perhaps even get a free AWS account and use cloudfront) to sponsor coderetreat with a free service that does satisfy our needs.

**Comment by rradczewski** [comment]
closing because https://github.com/coderetreat/orga-tasks/issues/1 solves this :+1:
