### ISSUE TITLE
All blog post links reference 404

### ISSUE THREAD

**Issue by svenlange** [coderetreat/coderetreat.github.io#31]
The "Continue" links on http://gdcr.coderetreat.org/blog/ point to 404

**Comment by rradczewski** [comment]
Hi @svenlange,
thanks for the bugreport! Should be fixed with [this commit](https://github.com/coderetreat/coderetreat.github.io/commit/1000d6740ee1442db58a8b5bd07d2febd305d9f5).

Thanks for reporting!
