### ISSUE TITLE
Countdown timer for next event is not displayed for Safari

### ISSUE THREAD

**Issue by thodorisbais** [coderetreat/coderetreat.github.io#342]
Tested for chrome and firefox and the countdown timer works perfectly fine.

However, for Safari (v1.11.2) this is not the case:
![screen shot 2018-09-29 at 08 32 29](https://user-images.githubusercontent.com/5684688/46242237-60d03980-c3c6-11e8-94be-57c87a1dec32.png)

**Comment by rradczewski** [comment]
Thanks @thodorisbais, totally forgot about that one. If I'd need to guess, I'd say its either the [`new Date(opts.targetDate)`](https://github.com/coderetreat/coderetreat.github.io/blob/master/_includes/countdown.liquid#L46) (safari maybe can't deal with the input format) or the [subtraction below](https://github.com/coderetreat/coderetreat.github.io/blob/master/_includes/countdown.liquid#L51)

Do you have safari at hand? If so, we could try fixing it together 😊

**Comment by thodorisbais** [comment]
Hey @rradczewski , yeah, sure, let's do this!
