### ISSUE TITLE
Convert Blogposts to Markdown

### ISSUE THREAD

**Issue by rradczewski** [coderetreat/coderetreat.github.io#36]
We want to make it easier to maintain the website. In order to do so, we'd like to convert all pages that don't necessarily need HTML to look *decent* to markdown.

We expect that this will decrease complexity when making changes to the styles and will help us stick to a general structure when writing new articles.

The blogposts in question are:

- [x] [2011-12-02-announcing-the-coderetreat-community-contribution-fund-(the-c3f).html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-02-announcing-the-coderetreat-community-contribution-fund-(the-c3f).html) - (419 words)
- [x] [2011-12-02-on-the-role-of-the-coderetreat-facilitator.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-02-on-the-role-of-the-coderetreat-facilitator.html) - (1541 words)
- [x] [2011-12-04-coderetreat---the-need-for-preparedness.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-04-coderetreat---the-need-for-preparedness.html) - (469 words)
- [x] [2011-12-04-coderetreat-2011-in-prague.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-04-coderetreat-2011-in-prague.html) - (932 words)
- [x] [2011-12-04-global-code-retreat-2011-in-berlin.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-04-global-code-retreat-2011-in-berlin.html) - (372 words)
- [x] [2011-12-04-global-day-code-retreat,-dresden,-germany.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-04-global-day-code-retreat,-dresden,-germany.html) - (307 words)
- [x] [2011-12-04-global-day-of-coderetreat---attendee-report.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-04-global-day-of-coderetreat---attendee-report.html) - (527 words)
- [x] [2011-12-04-global-day-of-coderetreat---organizing.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-04-global-day-of-coderetreat---organizing.html) - (555 words)
- [x] [2011-12-04-my-day-at-global-coderetreat-2011.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-04-my-day-at-global-coderetreat-2011.html) - (1174 words)
- [x] [2011-12-04-simple-design.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-04-simple-design.html) - (303 words)
- [x] [2011-12-05-code-retreat-global-day-retrospective.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-code-retreat-global-day-retrospective.html) - (305 words)
- [x] [2011-12-05-coderetreatin'.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-coderetreatin'.html) - (380 words)
- [x] [2011-12-05-gdcr-2011-in-durban,-south-africa.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-gdcr-2011-in-durban,-south-africa.html) - (1572 words)
- [x] [2011-12-05-gdcr-2011-in-prague.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-gdcr-2011-in-prague.html) - (1807 words)
- [x] [2011-12-05-gdcr-madrid-(video).html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-gdcr-madrid-(video).html) - (102 words)
- [x] [2011-12-05-gdcr11-in-london.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-gdcr11-in-london.html) - (490 words)
- [x] [2011-12-05-global-day-of-code-retreat,-chennai.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-global-day-of-code-retreat,-chennai.html) - (938 words)
- [x] [2011-12-05-global-day-of-coderetreat---notes-from-indianapolis.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-global-day-of-coderetreat---notes-from-indianapolis.html) - (715 words)
- [x] [2011-12-05-global-day-of-coderetreat-an-account-from-london.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-global-day-of-coderetreat-an-account-from-london.html) - (2690 words)
- [x] [2011-12-05-notes-from-bilbao-global-day-of-coderetreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-notes-from-bilbao-global-day-of-coderetreat.html) - (736 words)
- [x] [2011-12-05-the-hours-before.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-the-hours-before.html) - (529 words)
- [x] [2011-12-05-why-i-am-writing-this-week-for-csedweek.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-05-why-i-am-writing-this-week-for-csedweek.html) - (663 words)
- [x] [2011-12-06-coderetreat-a-first-time-facilitator's-view.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-06-coderetreat-a-first-time-facilitator's-view.html) - (1204 words)
- [x] [2011-12-06-global-day-of-coderetreat-in-buenos-aires.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-06-global-day-of-coderetreat-in-buenos-aires.html) - (42 words)
- [x] [2011-12-06-the-deep-end-&-the-global-day-of-code-retreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-06-the-deep-end-&-the-global-day-of-code-retreat.html) - (1270 words)
- [x] [2011-12-06-what-i-learned-in-the-global-day-of-code-retreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-06-what-i-learned-in-the-global-day-of-code-retreat.html) - (79 words)
- [x] [2011-12-07-coderetreat,-cracow,-2011---been-there,-done-that.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-07-coderetreat,-cracow,-2011---been-there,-done-that.html) - (43 words)
- [x] [2011-12-07-global-day-of-codereterat-in-budapest.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-07-global-day-of-codereterat-in-budapest.html) - (46 words)
- [x] [2011-12-07-global-day-of-coderetreat-at-barcelona.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-07-global-day-of-coderetreat-at-barcelona.html) - (59 words)
- [x] [2011-12-08-gdcr-in-milan.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-08-gdcr-in-milan.html) - (40 words)
- [x] [2011-12-08-global-day-of-code-retreat-in-calgary.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-08-global-day-of-code-retreat-in-calgary.html) - (828 words)
- [x] [2011-12-08-global-day-of-coderetreat-in-umeå,-sweden.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-08-global-day-of-coderetreat-in-umeå,-sweden.html) - (601 words)
- [x] [2011-12-08-notes-from-global-day-of-coderetreat-2011---skopje-(macedonia).html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-08-notes-from-global-day-of-coderetreat-2011---skopje-(macedonia).html) - (374 words)
- [x] [2011-12-09-code-retreat-roundup-github-toolbox.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-09-code-retreat-roundup-github-toolbox.html) - (1805 words)
- [x] [2011-12-09-global-day-of-code-retreat---vienna.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-09-global-day-of-code-retreat---vienna.html) - (555 words)
- [x] [2011-12-09-global-day-of-coderetreat---beijing!.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-09-global-day-of-coderetreat---beijing!.html) - (51 words)
- [x] [2011-12-11-global-day-of-code-retreat-dallas---thought-dump.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-11-global-day-of-code-retreat-dallas---thought-dump.html) - (60 words)
- [x] [2011-12-12-gdcr-sf-coderetreat-2011.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-12-gdcr-sf-coderetreat-2011.html) - (465 words)
- [x] [2011-12-12-global-day-of-code-retreat---nyc.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-12-global-day-of-code-retreat---nyc.html) - (36 words)
- [x] [2011-12-22-global-day-of-coderetreat-the-belgian-edition.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-22-global-day-of-coderetreat-the-belgian-edition.html) - (183 words)
- [x] [2011-12-23-london-coderetreat-video.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2011-12-23-london-coderetreat-video.html) - (123 words)
- [x] [2012-01-09-10-reasons-to-attend-a-code-retreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-01-09-10-reasons-to-attend-a-code-retreat.html) - (171 words)
- [x] [2012-01-09-don't-let-your-methods-look-like-this!.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-01-09-don't-let-your-methods-look-like-this!.html) - (182 words)
- [x] [2012-01-09-how-to-organize-a-code-retreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-01-09-how-to-organize-a-code-retreat.html) - (1654 words)
- [x] [2012-01-17-coderetreat-with-corey-haines.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-01-17-coderetreat-with-corey-haines.html) - (481 words)
- [x] [2012-01-18-first-coderetreat-of-2012.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-01-18-first-coderetreat-of-2012.html) - (243 words)
- [x] [2012-01-18-first-in-house-experiment.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-01-18-first-in-house-experiment.html) - (246 words)
- [x] [2012-01-18-new-session-idea-baby-steps.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-01-18-new-session-idea-baby-steps.html) - (152 words)
- [x] [2012-02-06-iquest-sibiu-romania-code-retreat-aftermath.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-02-06-iquest-sibiu-romania-code-retreat-aftermath.html) - (640 words)
- [x] [2012-02-09-announcement-c3f-sponsoring-black-girls-code-event.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-02-09-announcement-c3f-sponsoring-black-girls-code-event.html) - (588 words)
- [x] [2012-02-10-global-code-retreat-paris-2011.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-02-10-global-code-retreat-paris-2011.html) - (44 words)
- [x] [2012-02-13-retreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-02-13-retreat.html) - (552 words)
- [x] [2012-02-16-you-must-teach-to-be-taught.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-02-16-you-must-teach-to-be-taught.html) - (464 words)
- [x] [2012-02-28-notes-from-the-israeli-software-craftsmanship-group-code-retreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-02-28-notes-from-the-israeli-software-craftsmanship-group-code-retreat.html) - (858 words)
- [x] [2012-03-01-honing-the-craft-at-rhiza.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-03-01-honing-the-craft-at-rhiza.html) - (1723 words)
- [x] [2012-03-01-surviving-the-coderetreat-hangover.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-03-01-surviving-the-coderetreat-hangover.html) - (866 words)
- [x] [2012-03-22-memories-of-a-legacy-coderetreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-03-22-memories-of-a-legacy-coderetreat.html) - (80 words)
- [x] [2012-05-24-coderetreat-sri-lanka---2012.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-05-24-coderetreat-sri-lanka---2012.html) - (168 words)
- [x] [2012-07-24-code-retreat-with-corey-haines-@-dev-bootcamp.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-07-24-code-retreat-with-corey-haines-@-dev-bootcamp.html) - (578 words)
- [x] [2012-08-07-steel-city-ruby-conference-&-coderetreat-weekend.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-08-07-steel-city-ruby-conference-&-coderetreat-weekend.html) - (459 words)
- [x] [2012-08-23-global-day-of-coderetreat-2012.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-08-23-global-day-of-coderetreat-2012.html) - (817 words)
- [x] [2012-08-23-sassy,-challenging-and-wonderfully-infuriating---a-coderetreat-review.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-08-23-sassy,-challenging-and-wonderfully-infuriating---a-coderetreat-review.html) - (430 words)
- [x] [2012-08-25-testautomation-coderetreat-no.-1---a-report.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-08-25-testautomation-coderetreat-no.-1---a-report.html) - (798 words)
- [x] [2012-09-04-code-retreats-are-awesome!.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-09-04-code-retreats-are-awesome!.html) - (564 words)
- [x] [2012-09-05-corporate-wide-coderetreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-09-05-corporate-wide-coderetreat.html) - (87 words)
- [x] [2012-09-19-my-first-code-retreat---legacy-code-retreat-in-frankfurt-on-sep-15,-2012.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-09-19-my-first-code-retreat---legacy-code-retreat-in-frankfurt-on-sep-15,-2012.html) - (1767 words)
- [x] [2012-09-30-coderetreat-london-29.09.12.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-09-30-coderetreat-london-29.09.12.html) - (22 words)
- [x] [2012-10-09-codeweavers-coderetreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-10-09-codeweavers-coderetreat.html) - (958 words)
- [x] [2012-10-20-global-day-of-coderetreat-2012---nuremberg.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-10-20-global-day-of-coderetreat-2012---nuremberg.html) - (1236 words)
- [x] [2012-10-26-a-code-retreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-10-26-a-code-retreat.html) - (379 words)
- [x] [2012-11-04-changing-requirements.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-11-04-changing-requirements.html) - (149 words)
- [x] [2012-11-06-coderetreat-turku,-finland.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-11-06-coderetreat-turku,-finland.html) - (141 words)
- [x] [2012-11-19-coderetreat-münster,-germany-(22.09.2012).html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-11-19-coderetreat-münster,-germany-(22.09.2012).html) - (897 words)
- [x] [2012-12-09-code-retreat-cambridge.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-09-code-retreat-cambridge.html) - (661 words)
- [x] [2012-12-09-global-day-2012.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-09-global-day-2012.html) - (848 words)
- [x] [2012-12-09-global-day-of-code-retreat-in-amsterdam.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-09-global-day-of-code-retreat-in-amsterdam.html) - (1242 words)
- [x] [2012-12-10-barcelona-global-day-of-code-retreat-2012.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-10-barcelona-global-day-of-code-retreat-2012.html) - (391 words)
- [x] [2012-12-10-budapest-global-day-of-code-retreat-2012.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-10-budapest-global-day-of-code-retreat-2012.html) - (354 words)
- [x] [2012-12-11-global-day-coderetreat-at-mérida---venezuela,-2012.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-11-global-day-coderetreat-at-mérida---venezuela,-2012.html) - (1493 words)
- [x] [2012-12-11-global-day-of-coderetreat-2012-toronto-edition.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-11-global-day-of-coderetreat-2012-toronto-edition.html) - (990 words)
- [x] [2012-12-11-kudos-for-the-global-day-of-coderetreat.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-11-kudos-for-the-global-day-of-coderetreat.html) - (282 words)
- [x] [2012-12-12-amsterdam-code-retreat-2012.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-12-amsterdam-code-retreat-2012.html) - (1486 words)
- [x] [2012-12-12-global-day-of-code-retreat-–-minneapolis-edition.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-12-global-day-of-code-retreat-–-minneapolis-edition.html) - (817 words)
- [x] [2012-12-16-notes-from-global-day-of-coderetreat-2012---skopje-(macedonia).html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-16-notes-from-global-day-of-coderetreat-2012---skopje-(macedonia).html) - (326 words)
- [x] [2012-12-17-global-day-of-code-retreat-2012-in-cluj-napoca.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2012-12-17-global-day-of-code-retreat-2012-in-cluj-napoca.html) - (1135 words)
- [x] [2013-01-05-(one-of)-london's-gdcr-2012.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-01-05-(one-of)-london's-gdcr-2012.html) - (1922 words)
- [x] [2013-01-16-the-history-of-"taking-baby-steps".html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-01-16-the-history-of-"taking-baby-steps".html) - (228 words)
- [x] [2013-03-07-facilitators-note-on-coderetreat-in-joensuu.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-03-07-facilitators-note-on-coderetreat-in-joensuu.html) - (45 words)
- [x] [2013-03-11-taking-baby-steps.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-03-11-taking-baby-steps.html) - (297 words)
- [x] [2013-05-17-the-history-of-"brutal-refactoring-game".html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-05-17-the-history-of-"brutal-refactoring-game".html) - (343 words)
- [x] [2013-08-26-global-day-of-coderetreat-2013.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-08-26-global-day-of-coderetreat-2013.html) - (834 words)
- [x] [2013-09-11-coderetretreat-about-page-contest!.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-09-11-coderetretreat-about-page-contest!.html) - (1963 words)
- [x] [2013-10-06-thank-you-emily-for-the-legacy-code-retreat-collection.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-10-06-thank-you-emily-for-the-legacy-code-retreat-collection.html) - (291 words)
- [x] [2013-10-07-delete-your-code-video-contest.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-10-07-delete-your-code-video-contest.html) - (2905 words)
- [x] [2013-12-13-why-the-global-day-of-coderetreat-matters.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-12-13-why-the-global-day-of-coderetreat-matters.html) - (494 words)
- [x] [2013-12-20-facilitating-the-global-day-of-coderetreat-2013-in-amsterdam.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-12-20-facilitating-the-global-day-of-coderetreat-2013-in-amsterdam.html) - (1652 words)
- [x] [2013-12-25-thirty-developers-and-a-game-of-life-–-gdcr-2013-in-wrocław.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2013-12-25-thirty-developers-and-a-game-of-life-–-gdcr-2013-in-wrocław.html) - (542 words)
- [x] [2014-02-24-randori-fish-bowl-experiment.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2014-02-24-randori-fish-bowl-experiment.html) - (479 words)
- [x] [2014-03-08-revisiting-rescue-refactoring.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2014-03-08-revisiting-rescue-refactoring.html) - (462 words)
- [x] [2014-10-12-coderdojo-and-gdcr14.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2014-10-12-coderdojo-and-gdcr14.html) - (994 words)
- [x] [2014-11-19-coderetreat-the-toughest-constraint.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2014-11-19-coderetreat-the-toughest-constraint.html) - (248 words)
- [x] [2015-06-12-apac-day-of-coderetreat-on-jun-13.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2015-06-12-apac-day-of-coderetreat-on-jun-13.html) - (235 words)
- [x] [2015-07-09-self-organizing-team-s-exercise.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2015-07-09-self-organizing-team-s-exercise.html) - (1225 words)
- [x] [2015-07-20-self-organizing-team-2-footballs.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2015-07-20-self-organizing-team-2-footballs.html) - (607 words)
- [x] [2015-09-02-enabling-constraints.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2015-09-02-enabling-constraints.html) - (147 words)
- [ ] [2016-04-25-the-first-global-day-of-coderetreat-in-nokia-cd-site.html](https://github.com/coderetreat/coderetreat.github.io/tree/master/_posts/2016-04-25-the-first-global-day-of-coderetreat-in-nokia-cd-site.html) - (517 words)
- [x] [2015-09-02-enabling-constraints.html](https://github.com/coderetreat/coderetreat.github.io/tree/c359f128978260b919a12e3c78f2fee1c40e9660/_posts/2015-09-02-enabling-constraints.html) (145 words)
- [x] [2015-10-13-three-simulations-in-one-45-min-sprint.html](https://github.com/coderetreat/coderetreat.github.io/tree/c359f128978260b919a12e3c78f2fee1c40e9660/_posts/2015-10-13-three-simulations-in-one-45-min-sprint.html) (382 words)
- [x] [2016-04-09-announcing-global-day-of-coderetreat-2016.html](https://github.com/coderetreat/coderetreat.github.io/tree/c359f128978260b919a12e3c78f2fee1c40e9660/_posts/2016-04-09-announcing-global-day-of-coderetreat-2016.html) (299 words)
- [x] [2016-04-25-the-first-global-day-of-coderetreat-in-nokia-cd-site.html](https://github.com/coderetreat/coderetreat.github.io/tree/c359f128978260b919a12e3c78f2fee1c40e9660/_posts/2016-04-25-the-first-global-day-of-coderetreat-in-nokia-cd-site.html) (515 words)
- [x] [2016-07-23-how-to-participate-in-the-global-day-of-coderetreat-2016.html](https://github.com/coderetreat/coderetreat.github.io/tree/c359f128978260b919a12e3c78f2fee1c40e9660/_posts/2016-07-23-how-to-participate-in-the-global-day-of-coderetreat-2016.html) (438 words)
- [x] [2016-09-21-celebrating-100-gdcr-events-all-over-the-world-with-a-special-sur.html](https://github.com/coderetreat/coderetreat.github.io/tree/c359f128978260b919a12e3c78f2fee1c40e9660/_posts/2016-09-21-celebrating-100-gdcr-events-all-over-the-world-with-a-special-sur.html) (182 words)

The blogposts should keep their overall structure, some breaking changes are fine 👍 

We can do this one by one in a PR that is referencing this issue, I'll cross the posts off the list once they'r converted. Netlify will provide us with PR Previews 👍

**Comment by jdvr** [comment]
I am going to convert the first post.

I am commenting this to avoid waste time :)

**Comment by jdvr** [comment]
To remove html from preview and keep formatting the best idea is to use [post excerpt] (http://jekyllrb.com/docs/posts/#post-excerpts), it requires a little change on the blog.html template.  Maybe I could do this on a different PR after all post has been converted. What do you think?

**Comment by rradczewski** [comment]
Well spotted! I agree that doing that would make sense as it's more or less the standard way as far as I know. I'll open another issue for that 👍

**Comment by apandichi** [comment]
The following commits have added more blogposts from the archive. They need converting to Markdown as well: 1c08e5872a5443da5ae7af182bc79efe2335407f and 94d6ba6002a53a9c6c688a23267463e66004339d

**Comment by jdvr** [comment]
@rradczewski  Coudl you please add the new posts to the list and cross the one which have been converted?.

I will check the  author profile photo, but I think is better to work with the preview on the other issue (#43)

**Comment by rradczewski** [comment]
added the rest. Wow that's plenty 😓

**Comment by jdvr** [comment]
What do you think about change the strategy and create a PR for every five post instead of the one PR for each post.?

**Comment by rradczewski** [comment]
Good idea! ☺️👌

**Comment by rradczewski** [comment]
I'd like to quickly talk about the posts and whether we want to keep them on the mainblog at all. I'll bring this up with the other orgas next time we meet, but I wouldn't want you to put so much energy in to posts that maybe aren't relevant anymore.

**Comment by thodorisbais** [comment]
As of 13-03-2018, it was agreed that we will indeed try to convert the current html posts to markdown, but only for the ones that really deserve investing effort on. Otherwise, we leave those ones with html format, which implies they automatically become the major "to-be-decomissioned" candidates .
