### ISSUE TITLE
Fix Menu on Mobile

### ISSUE THREAD

**Issue by rradczewski** [coderetreat/coderetreat.github.io#39]
While most pages already look better on mobile than [the landingpage 😅 ](https://github.com/coderetreat/coderetreat.github.io/blob/master/index.html), the menu is in a bad state.

A foldable menu with access to the different links (similar to [how bootstrap](http://getbootstrap.com/components/#navbar) goes about this) and a viewport setting would be great here.

![image](https://user-images.githubusercontent.com/418117/28919176-9f3ae844-784c-11e7-971f-08c71ca44937.png)

**Comment by RabeaGleissner** [comment]
Hi @rradczewski 
I gave it a go https://github.com/coderetreat/coderetreat.github.io/pull/66
Let me know what you think! Happy to make any edits.

**Comment by rradczewski** [comment]
Made a few changes (e619c227c97deea37d399ecb9edabedd9d3addad, 9e42edce878b070724f4f72773ab26ddcbd83ce9, 2052f18ebfd60e4713e9b1295e2e7505c47ad6d6, 4c509cf74d68b4454bd1f8e596b939c6cbbe53ae) but looks good so far so I'm closing this
