### ISSUE TITLE
Merge information in README.md into /register-events page

### ISSUE THREAD

**Issue by rradczewski** [coderetreat/coderetreat.github.io#40]
Right now, the [Readme](https://github.com/coderetreat/coderetreat.github.io/blob/master/README.md) contains a lot of detailled information that does not appear on the [/register-event](https://github.com/coderetreat/coderetreat.github.io/blob/master/register-event.md) page.

Merging that information into the `/register-events` page will make it easier for hosts to create an event, as they have all the information in one place.

We can then change the `README` to focus on contributions, technical details of setting up the project, and so on.

**Comment by mplavcan** [comment]
I've made the register-event markdown a complete import of README.md

The only incompatibility is the embedded JSFiddle script.

**Comment by mplavcan** [comment]
Looks like GitHub guards against external scripts, and there's no conditional formatting available at the repository view level.  I've made it look pretty, but the JSFiddle link will still be inoperative there.
