### ISSUE TITLE
Remove "Cleveland introduction video"

### ISSUE THREAD

**Issue by coreyhaines** [coderetreat/coderetreat.github.io#478]
The video on the page that has the video of my introduction so many years ago feels very stale and outdated. Is it worth removing it? Is there a better video introduction?

**Comment by rachelcarmena** [comment]
Hi @coreyhaines,

Thanks for the warning! We're doing a lot of improvements in the website, but we think we still don't have another better video introduction :sweat_smile: 

However, we've just removed it and we've added History page content in About page (easier navigation).

Your video is still available in [your post](https://www.coderetreat.org/blog/2011/12/02/on-the-role-of-the-coderetreat-facilitator/) which is provided in facilitator materials.

We close this issue, but, please, reopen it in case there is another possible solution.

Thanks!!
