### ISSUE TITLE
separate facilitator names with comma in event list

### ISSUE THREAD

**Issue by tpd-opitz** [coderetreat/coderetreat.github.io#62]
My co facilitator and me have no twitter name, therefore the names are not separates visually.

**Comment by rradczewski** [comment]
Thanks for creating the issue @tpd-opitz. To provide some context here, we're talking about [this page](http://coderetreat.org/events/), more specifically this little annoyance:
![image](https://user-images.githubusercontent.com/418117/29535494-5442e11c-86ba-11e7-9e26-6f85a2ce3820.png).

Marking *Help wanted* as it should be fairly straight forward using the [`join`](https://help.shopify.com/themes/liquid/filters/array-filters#join) filter. If we want to make the `@twitterhandles` links, this might get a bit more complicated as we'd need to use something like [`forloop`](https://help.shopify.com/themes/liquid/objects/for-loops)

**Comment by tpd-opitz** [comment]
Yes, thats the entry I'm talking about.

**Comment by rradczewski** [comment]
Fixed in a1cd02034e54693f88c16342716e768aa20b1624
