### ISSUE TITLE
Group events listing by location

### ISSUE THREAD

**Issue by deniseyu** [coderetreat/coderetreat.github.io#63]
http://coderetreat.org/events has several events in Istanbul at the moment, but they are not grouped together.

It would be awesome to have a quick alphabetical sort or something in the view model to visually organise same-city (or same-country) events together!

**Comment by rradczewski** [comment]
I agree, there's a very crude listing [here](http://coderetreat.org/events/) but we could totally use a bigger map. We've opened a somewhat related ticket at #26 a few weeks ago.

OpenLayers seems to have pretty good support for [clusters](http://jorix.github.io/OL-FeaturePopups/examples/feature-popups.html), I'm sure we could come up with something like this.

Marking this as *Help Wanted* for the moment as it's fairly isolated and makes for a nice first contribution.

**Comment by mdizzy** [comment]
I was able to make the list sort by location, but the built in Liquid sort operation doesn't support nested properties so it only sorts the city.

I guess one way to fix it is to use a jquery tool that does the sorting...in fact I think I'll get that done.

**Comment by apandichi** [comment]
There is also this page that displays past events on a map, including listing the events by year.
http://coderetreat.org/events/past-events/

**Comment by apandichi** [comment]
So here is what I did to cluster the events on the map:
https://github.com/coderetreat/coderetreat.github.io/tree/clusteredMap
@rradczewski, please have a look. If it looks good, we can merge it to master.

**Comment by rradczewski** [comment]
Looks good @apandichi. Would've been easier if you would've opened a PR because netlify automatically adds [the deployment to the PR](https://clusteredmap--hairdresser-umbrellas-72171.netlify.com/).

Still left would be some more organization to the [table](https://clusteredmap--hairdresser-umbrellas-72171.netlify.com/events/) and maybe adding the map there again 👍

**Comment by apandichi** [comment]
Now that the pull request #85 is merged into master, I would say this issue is dealt with.
@mdizzy, does the latest code conflict with what you had going on regarding sorting the events? If so, let me know if I can help in any way.

**Comment by mdizzy** [comment]
no doesn't conflict at all. Is there a preference on a JS library? I think Knockout should be able to handle this without a problem.

Also, Heroku has a free tier that should be able to handle the load for the website. If not I'd be willing to donate monthly dynos for the site. This would let us run the site with a full database and backend framework.

**Comment by rradczewski** [comment]
I consider this fixed

**Comment by rradczewski** [comment]
Hi @mdizzy, thanks for the offer! We discussed Heroku briefly but decided that adding a backend would mean adding a lot of complexity that we don't really need. I will create an issue about migrating to [netlify](https://netlify.com/) next year as that would give us much more control about the build process, but that's about all we need right now.
