### ISSUE TITLE
Remind past GDCR facilitators to register to GDCR this year

### ISSUE THREAD

**Issue by apandichi** [coderetreat/coderetreat.github.io#89]
Send an email to past GDCR facilitators to remind them to register the GDCR for this year (if they want to organize one and if they didn't register already)

**Comment by rradczewski** [comment]
This is done with sending the mail, right @apandichi ?

**Comment by apandichi** [comment]
Yes, it is. I sent it to the Announcements and Discussion mailing lists.

**Comment by rradczewski** [comment]
Closing it in this case ;) 👍 thanks!
